Models/Visit.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace Clinic_Web.Models.Models
{
    public class Visit
    {
        
        
        public long VisitId { get; set; }
        [DisplayName("Pacjent")]
        public virtual long PatientId { get; set; }
        [DisplayName("Pacjent")]
        public virtual Patient patient { get; set; }
        [DisplayName("Lekarz")]
        public virtual long DoctorId { get; set; }
        [DisplayName("Lekarz")]
        public virtual Doctor doctor { get; set; }
        [DisplayName("Data")]
        [Required]
        
        [DataType(DataType.Date)]
        public DateTime date { get; set; }

        [DisplayName("Godzina")]
        [Required]
        public string hour { get; set; }
        public Visit()

        {


        }
        //  public List<String> get_free_hours() {
        //   return   this.doctor.get_free_visit_day(this.date);

        //   }

        /*
        public override bool Equals(Object ob)
        {

            Patient patient = this.patient;
            Patient patient2 = ((Visit)ob).patient;
            Doctor doctor = this.doctor;
            Doctor doctor2 = ((Visit)ob).doctor;
            DateTime date = this.date;
            DateTime date2 = ((Visit)ob).date;

            bool a = patient == (patient2);
            bool b = doctor == (doctor2);
            bool c = date.Equals(date2);
            bool d = false;

            if (a && b && c == true)
            {
                d = true;
            }


            return d;
        }
        */
    }
}

Controllers/VisitsController.cs
using Clinic_Web.Models;
using Clinic_Web.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Strona.Areas.Identity.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Clinic_Web.Controllers
{
    [Authorize(Roles = "Admin, Patient")]
    public class VisitsController : Controller
    {
        private readonly Database_controller _context;
        private readonly UserManager<Patient_account> _userManager;
        public string pesel;

        

        public VisitsController(Database_controller context, UserManager<Patient_account> userManager)
        {
            _context = context;
            _userManager = userManager;

           
        }

        // GET: Visits
        public async Task<IActionResult> Index()
        {

        var user = await _userManager.GetUserAsync(User);

            pesel = user.Pesel;
            var database_controller = _context.Visits.Where(c => c.patient.Pesel == user.Pesel).Include(v => v.doctor).Include(v => v.patient);
            return View(await database_controller.ToListAsync());
        }

        // GET: Visits/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .Include(v => v.doctor)
                .Include(v => v.patient)
                .FirstOrDefaultAsync(m => m.VisitId == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // GET: Visits/Create
        public async Task<IActionResult> Create()
        {


            var user = await _userManager.GetUserAsync(User);
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", nameof(Doctor.Name), nameof(Doctor.Surname));

            ViewData["PatientId"] = new SelectList(_context.Patients.Where(c => c.Pesel == user.Pesel), "PatientId", "Surname");

           

            return View();
        }

        [HttpGet]
        public List<DateTime> Updatedata(long x, DateTime data)
        {
            DateTime todaydata = DateTime.Today;
             var items = new List<DateTime>();
            if (data.DayOfYear < todaydata.DayOfYear)
            { return null; }
            Doctor doctor = new Doctor();
            doctor = _context.Doctors.Find(x); ;
            Visit visit = new Visit();
            visit.doctor = doctor;

            //  var result = _context.Visits.ToList().Where(y => y.DoctorId == x);
            //  doctor.Scheduled_visits = result;
            items = doctor.get_free_visit_day(data);
            // items = doctor.get_free_visit_day(data);
            return items;
        }

        // GET: Stock

        public ActionResult get_visits(int a)

        {

            Doctor doctor1 = new Doctor();
            doctor1 = _context.Doctors.Find(a);

            var items = new List<string>() { };



            // items = doctor1.get_free_visit_day_example();
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "Surname");

            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "Surname");
            ViewData["visit"] = new SelectList(items);
            return View();

        }

        // POST: Visits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VisitId,PatientId,DoctorId,date,hour")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                Doctor doctor = _context.Doctors.Find(visit.DoctorId);

                // doctor.get_free_visit_day(visit.date);
                // List<string> lista =  doctor.get_free_visit_day(visit.date);

                //  visit.doctor.Scheduled_visits.ToList().Add(visit);
                //visit.patient.Scheduled_visits.ToList().Add(visit);
                _context.Add(visit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "DoctorId", visit.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits.FindAsync(id);
            if (visit == null)
            {
                return NotFound();
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "Surname", visit.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "Surname", visit.PatientId);

            var items = Updatedata(visit.DoctorId, visit.date);
           
            var item = "";
            List<String> itemss = new List<String>();

           // for (var i = 0; i < items.Count; i++)
          //  {
             
             //   item = items[i].TimeOfDay.ToString();
             //   item = item.Substring(0, item.Length - 3);
                


          //  }
          
          //  ViewData["hour"] = new SelectList(items, "Minute" + "H);
            //new Multi
            return View(visit);
        }
        

        // POST: Visits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("VisitId,PatientId,DoctorId,date")] Visit visit)
        {
            if (id != visit.VisitId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.VisitId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "DoctorId", visit.DoctorId);
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientId", visit.PatientId);
            return View(visit);
        }

        // GET: Visits/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .Include(v => v.doctor)
                .Include(v => v.patient)
                .FirstOrDefaultAsync(m => m.VisitId == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var visit = await _context.Visits.FindAsync(id);
            _context.Visits.Remove(visit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitExists(long id)
        {
            return _context.Visits.Any(e => e.VisitId == id);
        }
    }
}

Views/Visits/Create.cshtml
@model Clinic_Web.Models.Models.Visit

@{
    ViewData["Title"] = "Utwórz wizytę";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center><h1>Utwórz wizytę</h1></center>

<h4>Wizyta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
              
                <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"> </select>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" id="iddoctor" class="form-control" onchange="goes()" asp-items="ViewBag.DoctorId">
                </select>
            </div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date"  id="chosendata" class="form-control" onchange="goes()" />
                <span asp-validation-for="date"  class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="hour" class="control-label"></label>
                <select asp-for="hour" class="form-control" asp-items="ViewBag.hour"></select>
            </div>

            <script>
                    function goes() {
                        var x = document.getElementById("iddoctor").value;
                        var y = document.getElementById("chosendata").value;
                     

                        if (y != "") {


                        $.ajax({
                      url: '@Url.Action("Updatedata", "Visits")',
                            dataType: "json",
                            data: { x, data: y} ,
                            success: function (data) {
                                if (data == null) {
                                    alert("Podałeś złą date");
                                   
                                    $('#hour').empty();
                                }
                                else {
                                    var items = data;

                                var item = "";
                                var itemss


                                for (var i = 0; i < items.length; i++) {
                                    item = items[i];
                                    item = item.replace("0001-01-01T", "").slice(0, -3);
                                    itemss += "<option value='" + item + "'>" + item + "</option>"

                                }
                                    $('#hour').html(itemss);
                                }
                            },
                             });
                        } };

            </script>



            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-primary" />
            </div>
            @if (ViewBag.Message != null)
            {
                <script charset="UTF-8" type="text/javascript">
            window.onload = function () {
                alert("@ViewBag.Message");
            };
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}




}

Views/Visits/Delete.cshtml
@model Clinic_Web.Models.Models.Visit

@{
    ViewData["Title"] = "Odwołaj";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Odwołaj wizytę</h1>
<br />


<div>
    <br />
    <br />
    <h4>Wizyta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.patient)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.patient.Name)
            @Html.DisplayFor(model => model.patient.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.doctor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.doctor.Name)
            @Html.DisplayFor(model => model.doctor.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.date)
            @Html.DisplayFor(model => model.hour)
        </dd>
    </dl>
    <h3>Czy jesteś pewny, że chcesz odwołać wizytę?</h3>
    <form asp-action="Delete">
        <input type="hidden" asp-for="VisitId" />
        <input type="submit" value="Odwołaj" class="btn btn-danger" /> |
        <a asp-action="Index">Cofnij</a>
    </form>
</div>

Views/Visits/Details.cshtml
@model Clinic_Web.Models.Models.Visit

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Visit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.patient)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.patient.PatientId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.doctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.doctor.DoctorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.date)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VisitId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Visits/Edit.cshtml
@model Clinic_Web.Models.Models.Visit

@{
    ViewData["Title"] = "Edycja";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h4>Edycja</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VisitId" />
            <div class="form-group">
                <label asp-for="PatientId" class="control-label"></label>
                <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"></select>
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" class="form-control" id="iddoctor" asp-items="ViewBag.DoctorId"></select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="date" class="control-label"></label>
                <input asp-for="date"  id="chosendata"  class="form-control" />
                <span asp-validation-for="date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hour" class="control-label"></label>
                <select asp-for="hour" class="form-control"  asp-items="ViewBag.hour"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Cofnij</a>
</div>


<script>
                    function goess() {
                        var x = document.getElementById("iddoctor").value;
                        var y = document.getElementById("chosendata").value;


                        if (y != "") {


                        $.ajax({
                      url: '@Url.Action("Updatedata", "Visits")',
                            dataType: "json",
                            data: { x, data: y} ,
                            success: function (data) {
                                if (data == null) {
                                    alert("Podałeś złą date");

                                    $('#hour').empty();
                                }
                                else {
                                    console.log("else");
                                    var items = data;

                                var item = "";
                                var itemss


                                for (var i = 0; i < items.length; i++) {
                                    item = items[i];
                                    item = item.replace("0001-01-01T", "").slice(0, -3);
                                    itemss += "<option value='" + item + "'>" + item + "</option>"

                                }
                                    $('#hour').html(itemss);
                                    console.log(itemss);
                                }
                            },
                             });
                        } };

</script>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Visits/Index.cshtml
@model IEnumerable<Clinic_Web.Models.Models.Visit>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista wizyt</h1>

<p>
    <a asp-action="Create">Utwórz nową wizytę</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Pacjent
            </th>
            <th>
                Lekarz
            </th>
            <th>
                Data
            </th>
            <th>
                Godzina
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.patient.toString2()
            </td>
            <td>
                @item.doctor.toString2()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hour)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VisitId">Edytuj wizytę</a> 
                |
                <a asp-action="Delete" asp-route-id="@item.VisitId">Odwołaj wizytę</a>
            </td>
        </tr>
}
    </tbody>
</table>